### ISSUE TITLE
Changing projects

### ISSUE THREAD

**Issue by jacksongs** [PyBossa/pbs#24]
Hello,

Is there an option for changing the default project?

For example, say if I create project A, then create project B, how can I then add tasks to project A?

Thanks, love your work.

**Comment by teleyinex** [comment]
Hi,

Yes, it is. When you create two different projects, you will have probably two different folders for each of them. Then, in each folder you will have different project.json files. Those files are the ones that identify your project. Thus, just access your other folder and run the same command for adding tasks. This time, the tasks will be uploaded to your current folder project. As simple as that.

Another option: have everything on the same folder. Then, create two project.json files: projecta.json, projectb.json. Use pbs command line option to specify the project file that you want to use and voila, it will work :-) (run pbs --help for more info).

All the best,

Daniel

PS: Thanks for the love! :heart_decoration:
